name: "GitHub Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version for the release (e.g. 1.2.3)"
        required: false
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Create GitHub Release
        uses: open-resource-discovery/github-release@02020c108b46638889308e063694c94258369eb2 # main
        with:
          tag-template: "v<version>"
          version: ${{ inputs.version }}
